### ISSUE TITLE
Starting tuning process on Raspberry Pi

### ISSUE THREAD

**Issue by Maikel-K** [ghoti57/evofw3#26]
Hi, im trying to check if my setup is working.
I was guessing to check if the autotune process could be run on my Pi.

i tried screen /dev/ttyUSB0 115200 as mentioned in this post:
https://github.com/ghoti57/evofw3/issues/6#issuecomment-783220165

But i doesnt work.
Any tips if this is possible to run on a RPI? If you need any info from me please let me know.
Im not the biggest expert on all of this but im eager to learn and fixed a lot of other things on the RPI.

**Comment by ghoti57** [comment]
The autotune process runs on the device not on the pi.
The pi just provides a serial terminal to communicate with the device and trigger autotune.

Why do you want to run autotune?
What device do you have?
What doesn't work?
Are you sure the device is connected to the pi as /dev/ttyUSB0

**Comment by Maikel-K** [comment]
Yes it got connected as ttyUSB0.

I want to run the autotune for two reasons:
Check that the communication between the unit and the pi is working

And

As mentioned in the above mentioned linked comment his advise was to run the autotune in the situation the unit will be running.

Or doesnt the autotune make an sense if it has been run already on a whole different location?

**Comment by ghoti57** [comment]
That is reporting that the device is receiving messages and reporting them to the pi over the USB connection.  It appears to be
functioning.

I repeat my question - what type of device do you have? Where did you get it?

Autotune is only necessary for devices that have been built with poor quality components.  It won't do anything useful if the device is well made.

What type of system are you trying to monitor?

**Comment by Maikel-K** [comment]
Im trying to monitor my Evohome system. If got the first gen color screen with the RFG100 internet gateway and that gateway is failing some times plus I can't see which room is requesting heat. So especially for the heatrequest I want to use this setup.

Im using these components.
![image](https://user-images.githubusercontent.com/10106756/145550839-abd09dee-14da-47d8-aea7-cc272be74fee.png)
![image](https://user-images.githubusercontent.com/10106756/145550850-2c3efd2e-3c1e-4ef4-a68c-56bb03ab7e24.png)
![image](https://user-images.githubusercontent.com/10106756/145550859-dab1fd15-db35-4026-befd-9592c8b56c61.png)


It's good to know that the module is working, I now know that I can try and use the Evogateway project of github user smar000. That won't put out data yet and I was wondering if that is because my reciever but that seems to be working/putting data on the serial at least.

**Comment by ghoti57** [comment]
So you have a self build device.

Autotune was written specifically to deal with some usb nanoCul devices that used poor quality components on the radio module.

You can run autotune but it probably won't make a significant difference.

**Comment by Maikel-K** [comment]
Yes it's a DIY indeed.

It's for the Crystal on the Nano or on the CC1101?

**Comment by ghoti57** [comment]
The problem was with the crystal on the cc1101.

**Comment by Maikel-K** [comment]
And the tune is saved on the Nano or on the chip of the CC1101?

**Comment by ghoti57** [comment]
It's saved on  the nano.  The cc1101 had no non-volatile storage.

**Comment by Maikel-K** [comment]
Okay, should it make any difference in which location you run the tune?

**Comment by Maikel-K** [comment]
I have run the autotune a few times now on the Pi and got following outcome:
!F F=216605

With this info saved to the unit with !FS im recieving good packages now.
So running it in the place where you are going to run it seems to make sense??

**Comment by Maikel-K** [comment]
By the way, are there any benefits of using the Atmega32U4 instead of the Atmega328p?

**Comment by ghoti57** [comment]
The 32u4 uses a hardware UART to connect to the CC1101 and has better RX performance than the 328p which uses a software UART.  TX performance should be the same.

**Comment by Maikel-K** [comment]
So if I want to send command trough the module it would work better with the 32U4, correct?

Would this unit work?

https://a.aliexpress.com/_m0k2pMw

Or this one:

https://a.aliexpress.com/_mPX8Vaq

**Comment by Maikel-K** [comment]
Hi Peter,

Would you suggest any of the two above units or do you have another suggestion?

Any suggestion for the radio C1101 board or keep the one I already have because it's working?

A friend of mine also wants a unit so I was thinking going for the 32U4 or sticking with the 328P which I'm using too.

**Comment by ghoti57** [comment]
I will release a batch of these in the next week.

https://indalo-tech.onlineweb.shop/SSM-D/p7844707_21129532.aspx

If you really want to continue with a self build device a 32u4 device is much better. Any 328p device with as usb interface uses the HW UART for the host usb interface.  On the 32u4 it is available for the cc1101 interface and packet RX is much better.

**Comment by Maikel-K** [comment]
Hi Peter,

The website says no shipping outside the UK...

So that makes that no option, I'm in the Netherlands.

Which of the two above 32U4 units would you recommend by looking at it?

**Comment by ghoti57** [comment]
Check the FAQ about delivery outside the UK which I've recently updated.  I can now shop to the Netherlands but you will have to pay VAT and a handling charge in the Netherlands.

**Comment by ghoti57** [comment]
Make sure you request a stock update to be informed about when they are available.

**Comment by ghoti57** [comment]
Not really an issue with the code
