### ISSUE TITLE
OpenTherm messages on UART branch?

### ISSUE THREAD

**Issue by smar000** [ghoti57/evofw3#3]
Hi Pete

Are opentherm messages generally working on your uart branch? I have been running this branch for the last few days, but do not seem to be getting any messages with command 3220 (https://github.com/Evsdd/The-Evohome-Protocol/wiki/3220:-OpenTherm-Message). This was working previously using one of your evofw2 branches, and would come through very regularly.

The only OpenTherm message that seems to be coming through for me is the ticker (1FD4).

Thanks.

**Comment by ghoti57** [comment]
I don't have an OTG so can't directly comment but other users are not saying there's a problem

There's nothing in the code that would cause a specific message to fail.

**Comment by smar000** [comment]
Ok thanks for the quick reply. 

I was just looking through my historical logs, and the messages appear to have stopped a couple of weeks ago - so unlikely to be related to my switchover to your `uart` branch firmware.

Thanks anyway.
