### ISSUE TITLE
Header wrong in Wiki

### ISSUE THREAD

**Issue by tomkooij** [ghoti57/evofw3#34]
I can seem to edit or send a PR for a wiki page.

The header description on: seems wrong:
https://github.com/ghoti57/evofw3/wiki/Message-Body#message-body
The wiki states:
```
00 RQ
01 W
10 I
11 RP
```
However in the code:
https://github.com/ghoti57/evofw3/blob/59ead112b0db1880e2318475b7e36160903275fa/message.c#L164
The order is:  { "RQ", "I","W","RP" }
`W` and `I` seem to be swapped in the Wiki page.

Correct order according to the code:

```
00 RQ
01 I
10 W
11 RP
```
(I'm quite sure this is wrong in the Wiki, as I handcrafted a packetheader based on the wiki, and an `I` message was recieved as `W` by a real HGI80)

I'd be glad to submit a PR to the wiki, but can't figure out how.

**Comment by ghoti57** [comment]
Thanks,  Wiki updated.
